### ISSUE TITLE
Server Crash after about a Min after launching

### ISSUE THREAD

**Issue by Tikkas** [cem3cem3/AppliedEcogisticsIssues#30] opened 2021-04-13 23:46 UTC
I added the mod to a server that has been runnning for about a week or so. After installing it the server seems to boot up fine and you can connect.  

It seems to work fine the few blocks i was able to test!
Useing 
Eco 0.9.2.4 R-156
&
1.23.0.9.2.4E

Console spams with the same key has already been added
Then after about a minitue or two just out right crashes
with

> [18:31:46.342] [28] [Error] [Eco] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at LiteDB.LiteCollection`1.Upsert(T entity)
   at Eco.Stats.Stats.Record(Int32 time, String collection, Single value)
   at Eco.Simulation.WorldLayers.SimStats.CollectStats(Double delta)
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)

 And

>[18:31:46.350] [28] [Error] [Eco] System.NotSupportedException: BSON type not supported
   at LiteDB.Engine.BufferReader.ReadElement(HashSet`1 remaining, String& name)
   at LiteDB.Engine.BufferReader.ReadDocument(HashSet`1 fields)
   at LiteDB.Engine.DatafileLookup.Load(PageAddress rawId)
   at LiteDB.Engine.DatafileLookup.Load(IndexNode node)
   at LiteDB.Engine.BasePipe.LoadDocument(IEnumerable`1 nodes)+MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.MoveNext()
   at LiteDB.Engine.QueryPipe.Select(IEnumerable`1 source, BsonExpression select)+MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader.Read()
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Eco.Stats.Stats.<>c__DisplayClass21_2.<SquashAggregatableStats>b__0()
   at Eco.Stats.Stats.SquashAggregatableStats()
   at Eco.Core.Utils.Threading.ActionUtils.<>c__DisplayClass1_0.<AsAsyncCancellableAction>b__0(CancellationToken _)
   at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.IntervalActionWorker.<>n__0(CancellationToken token)
   at Eco.Core.Utils.Threading.IntervalActionWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync()
   at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker)
   at Eco.Stats.Stats.Shutdown()
   at Eco.Server.PluginManager.<>c.<ShutdownAsync>b__35_0(PluginRegistration reg)

If you need anything else from me let me know id be glad to post it

[log_210413063002.log](https://github.com/cem3cem3/AppliedEcogisticsIssues/files/6307267/log_210413063002.log)

**Comment by cem3cem3** [comment] 2021-04-15 05:19
Thank you for the report, but I can't say if this is caused by my mod. The errors you get printed are fro the stats logging, which Applied Ecogistics should not be touching. 
If you could, try running the server with just Applied Ecogistics and check if the issue persists.

**Comment by cem3cem3** [comment] 2021-05-01 02:40
Closing for lack of information and because this issue doesn't seem to be caused by this mod specifically. Feel free to re-open if you can narrow it down a bit more.

**Closed as completed by cem3cem3** 2021-05-01 02:40 UTC
Labels: Need Informaion
